services:
  status:
    image: twinproduction/gatus:latest
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - ./config/config.yaml:/config/config.yaml
      - data:/data

volumes:
  data:

networks:
  proxy:
    name: cicd_proxy
    external: true