services:
  status:
    build:
      context: .
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - data:/data

volumes:
  data:

networks:
  proxy:
    name: cicd_proxy
    external: true
