services:
  status:
    image: lscr.io/linuxserver/healthchecks:latest
    environment:
      - TZ=Australia/Brisbane
      - SITE_ROOT=https://status.applyinnovations.au
      - SITE_NAME=Apply Innovations Status
      - SUPERUSER_EMAIL=alex@applyinnovations.com.au
      - SUPERUSER_PASSWORD=mead-awes-clumps
      # - ALLOWED_HOSTS= #optional
      # - APPRISE_ENABLED=False #optional
      # - CSRF_TRUSTED_ORIGINS= #optional
      # - DEBUG=True #optional
      # - DEFAULT_FROM_EMAIL= #optional
      # - EMAIL_HOST= #optional
      # - EMAIL_PORT= #optional
      # - EMAIL_HOST_USER= #optional
      # - EMAIL_HOST_PASSWORD= #optional
      # - EMAIL_USE_TLS= #optional
      # - INTEGRATIONS_ALLOW_PRIVATE_IPS= #optional
      # - PING_EMAIL_DOMAIN= #optional
      # - RP_ID= #optional
      # - SECRET_KEY= #optional
      # - SITE_LOGO_URL= #optional
    volumes:
      - healthchecks-config:/config
    restart: unless-stopped
    networks:
      - proxy

volumes:
  healthchecks-config:

networks:
  proxy:
    name: cicd_proxy
    external: true
